### ISSUE TITLE
Jet Rocket 2 Stream Error

### ISSUE THREAD

**Issue by poudink** [Gota7/Citric-Composer#4]
This is an issue with Jet Rocket II's music. It's located in the streams folder in the rom/cia/whatever. When selecting a stream, this error appears:
```
Unhandled exception has occured in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.
InvalidArgument=Value of '16' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '16' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at Citric_Composer.MainWindow.DoInfoStuff()
   at Citric_Composer.EditorBase.tree_NodeMouseClick(Object sender, TreeNodeMouseClickEventArgs e)
   at System.Windows.Forms.TreeView.OnNodeMouseClick(TreeNodeMouseClickEventArgs e)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4069.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Citric Composer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Downloads/Citric-Composer-master/Citric-Composer-master/Citric%20Composer/Citric%20Composer/bin/Release/Citric%20Composer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ScintillaNET
    Assembly Version: 3.6.3.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Downloads/Citric-Composer-master/Citric-Composer-master/Citric%20Composer/Citric%20Composer/bin/Release/Citric%20Composer.exe
----------------------------------------
CSCore
    Assembly Version: 1.2.1.2
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Downloads/Citric-Composer-master/Citric-Composer-master/Citric%20Composer/Citric%20Composer/bin/Release/Citric%20Composer.exe
----------------------------------------
Syroot.BinaryData
    Assembly Version: 2.0.2.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Downloads/Citric-Composer-master/Citric-Composer-master/Citric%20Composer/Citric%20Composer/bin/Release/Citric%20Composer.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```
This happens with each of the streams. Despite the error, the stream will remain playable, but it will impossible to right click it, since clicking it in the list in any way will cause the error to pop up. This blocks off several options.

**Comment by Gota7** [comment]
Is this for the Streams section or for a Stream in the file list?

If it is just a Stream, there is either something going on with the File Id, Stream Type, or Prefetch File Id.

If it is a Stream File, then there is something weird going on with the Groups. These are the only things that use combo boxes.

**Comment by poudink** [comment]
it happens in the Sound Streams section but not in the Files section
